nominal:
  goal:
    coordinates:
      - 0.0
      - 3.0
      - 0.5
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    gain:
    - [0.0, 0.2, 0.0, 0.0, 0.2, 0.0, 0.0]
    - [0.2, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
    - [0.0, 0.0, -5.4772, 0.0, 0.0, -5.5637, 0.0]
    u_ref:
      - 0.0
      - 0.0
      - 0.0
      - 10.8 
      # - 11.5
  frequency: 50.0

limits:
  max_thrust: 61000  # (0-16) -> (0-65535), ~40000 is hover
  min_thrust: 16000
  # max_roll: 30.0
  max_roll: 5.0
  max_pitch: 30.0
  max_yawrate: 30.0

asif:
  gamma: 0.1
  slack: False  # True doesn't work

initial_cbf:
  Parameters:
    scaling: [10.0, 4.0, 0.5, 0.5]
    center: [3.0, 0.7, 0.0, 0.0]
    offset: 2.0