controller_type: "PD"  # one of ["PD", "HJR"]
nominal:
  goal:
    coordinates:
      - 8.0
      - 4.0
      - 0.79
    padding:
      - 0.05
      - 0.05
      - 0.5
    max_time: 30.0
    time_intervals: 101
    solver_accuracy: "high"
  frequency: 20.0
external:
  buffer_time: 1.0  # seconds
  mod_buffer_time: 5.0  # seconds
limits:
  max_vel: 1.0
  min_vel: 0.1
  max_omega: 0.2

asif:
  gamma: 0.2
  slack: True

initial_cbf:
  Parameters:
    scaling: [2.0, 2.0, 1.0]
    center: [2.0, 2.0, 1.0]
    offset: 5.0

  
